### ISSUE TITLE
Problem with inc file and beginning of the any file

### ISSUE THREAD

**Issue by ManFizz** [Hexer10/SPCode#49] opened 2021-01-06 16:48 UTC
![image](https://user-images.githubusercontent.com/57350669/103795513-d0e3c480-5091-11eb-977f-403518a508f8.png)
If you write "#define" in the .inc file (46 line), then the spcode will not start.
If you write [ at the beginning of the file, then the spcode will crash.
version 1.6.2.1

**Comment by Hexer10** [comment] 2021-01-06 17:19
I could reproduce the crash with `[` thanks for reporting!
I wasn't able to make the ide crash with `#define` could you provide more context or share the file that is making the ide crash, also check in the IDE directory there should be a crashlog (pick the latest after the IDE has crashed)

**Comment by ManFizz** [comment] 2021-01-06 18:25
I was unable to produce this bug again, but I have a crash log
[CRASH_17488968.txt](https://github.com/Hexer10/SPCode/files/5777530/CRASH_17488968.txt)

**Comment by Natanel-Shitrit** [comment] 2021-02-13 19:00
The bug with the `#define` should be fixed from next release.
I couldn't reproduce the `[` bug, i will talk to @Hexer10 for some help i and i hope to fix that too.

**Comment by Natanel-Shitrit** [comment] 2021-02-13 19:34
Not reproduceable anymore, re-open if you can constantly reproduce it.
Closed 😄

**Closed by Natanel-Shitrit** 2021-02-13 19:34 UTC
Labels: bug
